// scripts/set-env-dev.mjs
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../src/environments/environment.dev.ts');

const content = `// Auto-generated by scripts/set-env-dev.mjs – do not edit by hand.
export const environment = {
  production: false,
  apiBaseUrl: '/api',
} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf-8');
console.log('[set-env-dev] Written', outputPath);
