// scripts/set-env.mjs
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../src/environments/environment.prod.ts');

const required = ['API_URL', 'SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`[set-env] Missing required env vars: ${missing.join(', ')}`);
  process.exit(1);
}

const apiBaseUrl    = process.env['API_URL'].replace(/\/$/, '') + '/api';
const supabaseUrl   = process.env['SUPABASE_URL'];
const supabaseAnon  = process.env['SUPABASE_ANON_KEY'];

const content = `// ⚠️  Auto-generated by scripts/set-env.mjs – do not edit by hand.
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnon}',
  apiBaseUrl: '${apiBaseUrl}',
} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf-8');
console.log('[set-env] Written', outputPath);
