// ⚠️  Auto-generated by scripts/set-env.mjs – do not edit by hand.
export const environment = {
  production: true,
  supabaseUrl: 'https://ftkmalbkbyaqxxhxilyh.supabase.co',
  supabaseAnonKey: 'sb_publishable_ttlqyzHavO78uscEpnlbnQ_3VsDnG_N',
  apiBaseUrl: '/api',
} as const;
